name: drone
favicon: null
layout_spectrum: 0.615709
typography_spectrum: 0.651182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.471757
  lightness: 0.5625
  saturation: 0.412716
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
