analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.471757
  lightness: 0.25072
  rhythmicContrast: 0.873167
  saturation: 0.412716
cta: {}
layout_spectrum: 0.615709
name: drone
opengraph: {}
purpose: {}
typography_spectrum: 0.651182
